get_order_id = "select order.id from customer, order, purchased where customer.id={customerID} and order.status={status} and customer.id=purchased.customerID and order.id=purchased.orderid"
insert_into_order = "insert into order (status) values ({status})"
insert_into_purchased = "insert into purchased (customerID, orderID) values ({customer_ID},{order_ID})"
insert_into_includes = "insert into includes (orderID, productID) values ({order}, {productID})"
get_cart = "select product.name, product.price, product.weight from product, includes where product.ID = includes.product_ID and indludes.order_ID={order}"
get_free_drones_and_capacities = "select drone.id, drone.capacity from drone where drone.availibility=1"
get_order_weights = "select product.weight from product, includes where includes.orderID={order} and includes.productID=product.ID"
get_product_availability_by_id = "select ingredient.amount from contains, ingredient where contains.productID={prod_ID} and contains.ingredientID=ingredient.ID"
get_order_products = "select productID from includes where orderID={order}"
get_order_type = None
set_drone_to_busy = "update drone set drone.status=1 where drone.id={drone_id}"
set_order_to_purchased = "update order set order.status=1 where order.id={order}"
insert_into_delivers = "insert into delivers (droneID, orderID) values ({drone_id}, {order})"
get_product_ingreds_id_and_amount = "select ID, amount from contains where productID={prod_ID}"
update_ingreds_by_id = "update ingredient set amount={newamount} where ID={ingred_ID}"
update_dest_and_time = "update order set order.destlong={dest_long}, order.destlat{dest_lat}, order.time={time_to_dest} where order.id={order}"
get_all_products = "select * from product"